config/routes.rb
Rails.application.routes.draw do
  # devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # root 'users#index'
  # get '/users/:id', to: 'users#show'
  # get 'users/:id/posts', to: 'posts#index'
  # get 'users/:id/posts/:post_id', to: 'posts#show'
  devise_for :users, controllers: { sessions: 'users/sessions' }
  devise_scope :user do
    get '/users/sign_in', to: 'users/sessions#new'
    get '/users/sign_out', to: 'users/sessions#destroy'
  end

  resources :users, only: [:index, :show] do
    resources :posts, only: [:new, :create, :index, :show, ] do
      resources :comments, only: [:new, :create]
      resources :likes, only: [:create]
    end
  end

  # Defines the root path route ("/")
  # root "articles#index"
  root "users#index"
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :comments
  has_many :likes
  belongs_to :author, class_name: 'User'

  validates :title, presence: true, length: { maximum: 250 }
  validates :comments_counter, :likes_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  after_save :update_post_counter

  def update_post_counter
    author.increment!(:posts_counter)
  end

  def five_recent_comments
    comments.order(created_at: :desc).limit(5)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @user = User.find(params[:user_id])
    # @posts = @user.posts.includes(:comments)
    @posts = Post.where(author_id: @user.id)
  end

  def new
    @post = Post.new
    respond_to do |format|
      format.html { render :new, locals: { post: @post } }
    end
  end

  def create
    @post = Post.new(helper_params)
    @post.author_id = params[:user_id]
    @post.comments_counter = 0
    @post.likes_counter = 0
    if @post.save
      flash[:success] = 'Added succesfully'
      redirect_to user_posts_path(params[:user_id])
    else
      flash.now[:error] = 'question could not  be saved'
      render :new, locals: { post: post }
    end
  end

  def show
    @user = User.find(params[:user_id])
    @posts = Post.where(author_id: @user.id)
    @post = Post.find(params[:id])
  end

  private

  def helper_params
    params.require(:my_post).permit(:title, :text)
  end
end

app/views/posts/_form.html.erb
<%= form_with model: @post, url: user_posts_path, method: :post, local: true, scope: :my_post do |f| %>
  <div>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <div>
    <%= f.label :text %>
    <%= f.text_field :text %>
  </div>
    <%= f.submit "Create Post" %>
<% end %>

app/views/posts/index.html.erb
<div id="container_index_posts">
  <div id="container_container">
      <img id="container_container_img" src="<%= @user.photo %>" alt="user profile">
      <div id="container_container_div">
        <h3><%= @user.name %></h3>
        <p>Number of posts: <%= @user.posts_counter %></p>
      </div>
    </div>
    <% @posts[0...5].each do |post|%>
    <div id="show_container_user_id">
      <h3>Title: <%= link_to post.title, user_post_path(@user, post) %></h3>
      <p><%= post.text %></p>
      <h4>Comments <%= post.comments_counter %> likes: <%= post.likes_counter %></h4>
      <%= form_with url: "/users/#{@user.id}/posts/#{post.id}/likes" do |f| %>
        <%= f.submit "like posts"%>
      <% end %>
    </div>
    <% @comments=Comment.where(post_id: post.id) %>
    <div id="container_index_posts_comments_container">
    <% @comments.each do |comment| %>
        <div id="container_index_posts_comments">
        <%= @user.name%>: <%= comment.text%>
        </div>
    <% end %>
    </div>
  <% end %>
  <div id="show_container_post_button_container">
    <button id="show_container_post_button">Pagination</button>
  </div>
</div>

app/views/posts/new.html.erb
<% @comments=Comment.where(post_id:@post.id) %>
  <div id="container_index_posts_show_comments_container">
    <% @comments.each do |comment| %>
      <p><%=@user.Name%>: <%= comment.id %>  Comment: <%= comment.Text %></p>
    <% end %>
  </div>
  </div>
<%= render "form"%>

app/views/posts/show.html.erb
<div id="post_show_container">
  <div id="post_show_container_upper">
  <div id="post_show_container_header">
    <h3>Post #<%= @post.id%> by <%=@user.name%> Title: <%= @post.title%></h3>
    <h5>Comments:<%= @post.comments_counter%> Likes: <%=@post.likes_counter%></h5>
  </div>
  <p><%= @post.text %></p>
  </div>
  <% @comments=Comment.where(post_id:@post.id) %>
  <div id="container_index_posts_show_comments_container">
    <% @comments.each do |comment| %>
      <p><%=@user.name%>: <%= comment.text%></p>
    <% end %>
  </div>
</div>